name: Check-AWS-Release

on: 
  push:
    branches: ['master']

jobs:
  check-aws:
    name: Check-AWS-Release
    environment: nOpsDeployment
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.NOPS_ROLE }}
          role-session-name: GitHubActionsDeployCF
          aws-region: us-west-2

