name: Check Release

on: 
  pull_request:
    branches:
      - 'deploy'
jobs:
  check-release-pr:
    name: Check Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check release duplication
        run: |
          ./deploy_scripts/check_release.sh

      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Run Python unit tests
        run: |
          make test
