name: Releases

on: 
  push:
    branches: ['test']

jobs:
  release-new-package-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: truclk


      - name: Build package
        run: |
          make package
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Release package
        run: |
          release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}


